### ISSUE TITLE
Can you please quote my project in the README

### ISSUE THREAD

**Issue by cortinico** [shafi-dayatar/SportsAnalytics#2]
Hey @shafi-dayatar 

Can I ask you to quote my project in the README? Looks like you used https://github.com/cortinico/myonnaise right? :)

Also I released another version of the library if that might help you.
Best

**Comment by shafi-dayatar** [comment]
Done!
Thanks again for the library and I am so sorry not to mentioned your library, as it was incomplete

**Comment by cortinico** [comment]
Thanks <3
